
program = damage

include $(JIVEDIR)/makefiles/packages/app.mk
include $(JIVEDIR)/makefiles/packages/fem.mk
include $(JIVEDIR)/makefiles/packages/util.mk
include $(JIVEDIR)/makefiles/packages/geom.mk
include $(JIVEDIR)/makefiles/packages/implict.mk
include $(JIVEDIR)/makefiles/packages/gl.mk
include $(JIVEDIR)/makefiles/prog.mk
