
program = elastic

include $(JIVEDIR)/makefiles/packages/util.mk
include $(JIVEDIR)/makefiles/packages/algebra.mk
include $(JIVEDIR)/makefiles/packages/solver.mk
include $(JIVEDIR)/makefiles/packages/fem.mk
include $(JIVEDIR)/makefiles/packages/geom.mk
include $(JIVEDIR)/makefiles/prog.mk

