/*
 *
 *  This module reads a mesh generated by Gmsh and stores it in globdat
 *  as NodeSet and ElementSet object.
 *
 *  The GroupInputModule is embedded for definition of NodeGroups and
 *  ElementGroups.
 *
 *  This Module does not define any constraints!
 *
 *  Frans van der Meer, August 2008 
 *  
 */

#ifndef GMSH_INPUT_MODULE_H
#define GMSH_INPUT_MODULE_H

#include <jem/io/FileReader.h>
#include <jem/util/Properties.h>
#include <jive/app/Module.h>
#include <jive/fem/XElementSet.h>
#include <jive/fem/XNodeSet.h>
#include <jive/fem/ElementGroup.h>
#include <jive/util/Assignable.h>

#include "GroupInputModule.h"

using namespace jem;

using jem::io::FileReader;
using jem::util::Properties;
using jive::StringVector;
using jive::app::Module;
using jive::fem::XElementSet;
using jive::fem::ElementGroup;
using jive::fem::XNodeSet;
using jive::util::Assignable;

typedef XElementSet         XElemSet;
typedef ElementGroup        ElemGroup;

//-----------------------------------------------------------------------
//   class GmshInputModule
//-----------------------------------------------------------------------

class GmshInputModule : public Module
{

 public:

  typedef GmshInputModule    Self;
  typedef Module             Super;

  static const char*        TYPE_NAME;
  static const char*        FILE_NAME;
  static const char*        DIM;
  static const char*        DO_ELEM_GROUPS;
  static const char*        MAKE_LOW_ORDER;
  static const char*        GMSH_ELEMS;
  static const char*        LOW_ORDER_ELEMS;

  explicit                  GmshInputModule

    ( const String&           name   = "gmshInput" );

  virtual Status            init

    ( const Properties&       conf,
      const Properties&       props,
      const Properties&       globdat );

  static Ref<Module>        makeNew

    ( const String&           name,
      const Properties&       conf,
      const Properties&       props,
      const Properties&       globdat );

 protected:

  virtual                  ~GmshInputModule  ();

 private:

  bool                     doElemGroups_;
  bool                     lowOrderCopy_;

  idx_t                    rank_;
  idx_t                    numNodes_;
  idx_t                    numElems_;

  String                   fileName_;

  Ref<FileReader>          iFile_;

  Assignable<XElemSet>     elems_;
  Assignable<XNodeSet>     nodes_;
  Ref<GroupInputModule>    groupInput_;

 private:

  void                     configure_ 

    ( const Properties&       conf,
      const Properties&       props,
      const Properties&       globdat );

  void                     initSets_ 

    ( const Properties&       globdat );

  void                     readMesh_ 

    ( const Properties&       globdat );

  void                     makeLowOrderCopy_

    ( const Properties&       globdat );

  void                     openFile_ ();

  void                     closeFile_ ();

  void                     checkHighOrderMesh_ ();
};

#endif
